version: "3"
services:
    app:
        build:
            context: ./
        environment:
            APP_ENV: local
            DB_HOST: database
        networks:
            - jobstack
        ports:
            - "8003:80"
        volumes:
            - ./:/app
            - /app/vendor
            - /app/node_modules

    database:
        image: voyageapp/postgres:14.2
        ports:
            - "54325:5432"
        networks:
            - jobstack
networks:
    jobstack:
        driver: bridge
